[package]
name = "ptest"
version = "0.1.0"
authors = ["david.brown"]
edition = "2018"

[dependencies]
chrono = "0.4"
env_logger = "0.9.0"
failure = "0.1.8"
log = "0.4.17"
num_cpus = "1.13.1"
std-semaphore = "0.1"
yaml-rust = "0.4"

[dependencies.clap]
version = "4.0"
features = ["derive"]
