/*******************************************************************************
 * File Name: boot_rng.c
 *
 *******************************************************************************
* Copyright 2025, Cypress Semiconductor Corporation (an Infineon company) or
* an affiliate of Cypress Semiconductor Corporation.  All rights reserved.
*
* This software, including source code, documentation and related
* materials ("Software") is owned by Cypress Semiconductor Corporation
* or one of its affiliates ("Cypress") and is protected by and subject to
* worldwide patent protection (United States and foreign),
* United States copyright laws and international treaty provisions.
* Therefore, you may use this Software only as provided in the license
* agreement accompanying the software package from which you
* obtained this Software ("EULA").
* If no EULA applies, Cypress hereby grants you a personal, non-exclusive,
* non-transferable license to copy, modify, and compile the Software
* source code solely for use in connection with Cypress's
* integrated circuit products.  Any reproduction, modification, translation,
* compilation, or representation of this Software except as specified
* above is prohibited without the express written permission of Cypress.
*
* Disclaimer: THIS SOFTWARE IS PROVIDED AS-IS, WITH NO WARRANTY OF ANY KIND,
* EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, NONINFRINGEMENT, IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE. Cypress
* reserves the right to make changes to the Software without notice. Cypress
* does not assume any liability arising out of the application or use of the
* Software or any product or circuit described in the Software. Cypress does
* not authorize its products for use in any products where a malfunction or
* failure of the Cypress product may reasonably be expected to result in
* significant property damage, injury or death ("High Risk Product"). By
* including Cypress's product in a High Risk Product, the manufacturer
* of such system or application assumes all risk of such use and in doing
* so agrees to indemnify Cypress against all liability.
*******************************************************************************/

#include <stddef.h>
#include <stdint.h>
#include "cmsis_compiler.h"
#include "boot_rng.h"

/* PRNG parameters */
#define PRNG_A  13U
#define PRNG_B  17U
#define PRNG_C  5U

#define PRNG_DEFAULT_SEED  (0xB59A9242U)

/* Initialize PRNG by default values
 * (32 bit numbers of Hamming distance 16 bits.) */
static uint32_t prng_rnd;

static bool rng_is_initialized = false;


/*******************************************************************************
 * Function Name: boot_rng_get_rnd_num_length
 *******************************************************************************
 * \brief Return size of rnd number that is generated by this RND
 *
 * return  uint32_t
 *
 ******************************************************************************/
uint32_t boot_rng_get_rnd_num_length(void)
{
    return sizeof(uint32_t);
}


/*******************************************************************************
 * Function Name: boot_rng_is_initialized
 *******************************************************************************
 * \brief Return status PRNG initialization
 *
 * return true   PRNG initialized
 *        false  PRNG not initialized
 *
 ******************************************************************************/
bool boot_rng_is_initialized(void)
{
    return rng_is_initialized;
}


/*******************************************************************************
 * Function Name: boot_rng_initialization_done
 *******************************************************************************
 * \brief The function must be called if PRNG initialization is done.
 *
 *
 ******************************************************************************/
void boot_rng_initialization_done(void)
{
     rng_is_initialized = true;
}


/*******************************************************************************
 * Function Name: boot_rng_init_seed
 *******************************************************************************
 * \brief Set PRNG seed
 *
 ******************************************************************************/
void boot_rng_init_seed(uint32_t seed)
{
    if (!boot_rng_is_initialized())
    {
        prng_rnd = seed;
    }
}


/*******************************************************************************
 * Function Name: boot_rng_init
 *******************************************************************************
 * \brief Initialize initialize PRNG seed by TRNG value. By default it is used
 *        hardcoded PRNG_DEFAULT_SEED value as PRNG seed. Each platform should
 *        have its own implementation of this function to use true random
 *        number as PRNG seed(i.e. from TRNG)
 *
 * return true   if RNG initialization is successful
 *        false  in other cases
 *
 ******************************************************************************/
__WEAK bool boot_rng_init(void)
{
    bool ret = false;

    do
    {
        /* Prevent PRNG double initialization */
        if(boot_rng_is_initialized())
        {
            ret = true;
            break;
        }

        boot_rng_init_seed(PRNG_DEFAULT_SEED);
        boot_rng_initialization_done();
        ret = true;

    } while(false);

    return ret;
}


/*******************************************************************************
 * Function Name: boot_rng_random_generate
 *******************************************************************************
 * \brief Generate 32-bit random number by PRNG.
 *
 ******************************************************************************/
uint32_t boot_rng_random_generate(void)
{
    if (!boot_rng_is_initialized())
    {
        /* If PRNG initialized is failed then stop booting for secure reasons */
        if(!boot_rng_init())
        {
            while(true) {
                __WFI();
            }
        }
    }

    /* Generate a random number by PRNG */
    prng_rnd ^= (prng_rnd << PRNG_A);
    prng_rnd ^= (prng_rnd >> PRNG_B);
    prng_rnd ^= (prng_rnd << PRNG_C);

    return prng_rnd;
}
