/*
 * Copyright (c) 2019 Nordic Semiconductor ASA
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/* This file mocks zephyr's autogenerated DT output header file */

#ifndef __DEVICETREE_H__
#define __DEVICETREE_H__

#define DT_FLASH_AREA_IMAGE_0_ID 1
#define DT_FLASH_AREA_IMAGE_1_ID 2
#define DT_FLASH_AREA_IMAGE_SCRATCH_ID 3
#define DT_FLASH_AREA_IMAGE_2_ID 4
#define DT_FLASH_AREA_IMAGE_3_ID 5

#endif /*__DEVICETREE_H__*/
