subdir-ccflags-y += -I$(PROJECT)/boot/bootutil/include
subdir-ccflags-y += -I$(PROJECT)/boot/zephyr/include

obj-y += main.o
obj-y += flash_map.o hal_flash.o os.o
obj-y += keys.o

obj-y += ../bootutil/src/
