/*
 * Copyright (c) 2022 Legrand North America, LLC.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <zephyr/ztest.h>
#include <bootutil/sign_key.h>

#include "mcuboot_config/mcuboot_config.h"

/**
 * @addtogroup t_mcuboot_app
 * @{
 * @defgroup t_mcuboot
 * @}
 */

/* HACK: When building for this test suite the mcuboot_app renamess
 * "void main(void)" * to be "void mcuboot_main(void)" since the
 * ztest framework provides the implementation for "main()".
 */
extern void mcuboot_main(void);

/*
 * NOTE: *_pub_key and *_pub_key_len are autogenerated based on the provided
 *       key file. If no key file was configured, the array and length must be
 *       provided and added to the build manually.
 */
const struct bootutil_key bootutil_keys[] = {
    {
	.key = NULL,
	.len = NULL,
    },
};
const int bootutil_key_cnt = 1;

ZTEST(mcuboot_app_main, test_main)
{
    mcuboot_main();
}

ZTEST_SUITE(mcuboot_app_main, NULL, NULL, NULL, NULL, NULL);
